#!/bin/sh

set -euo pipefail

help() {
    echo "Usage: $0"
    echo "SOURCE_URL, DESTINATION_PATH environment variables must be set"
}

OWNER_USERID="${OWNER_USERID:-}"
CLEAN_DESTINATION_PATH=""
AWS_SECRET_ACCESS_KEY_FILE=""
AWS_ACCESS_KEY_ID_FILE=""

if [ -z "$SOURCE_URL" ] || [ -z "$DESTINATION_PATH" ]
then
    help
    exit 1
fi

if [ -n "$CLEAN_DESTINATION_PATH" ]
then
    rm -rf "$DESTINATION_PATH/*"
fi

if [ -n "$AWS_ACCESS_KEY_ID_FILE" ]; then
    export AWS_ACCESS_KEY_ID="$(cat $AWS_ACCESS_KEY_ID_FILE)"
fi

if [ -n "$AWS_SECRET_ACCESS_KEY_FILE" ]; then
    export AWS_SECRET_ACCESS_KEY="$(cat $AWS_SECRET_ACCESS_KEY_FILE)"
fi

aws s3 cp "$SOURCE_URL" - | tar -C "$DESTINATION_PATH" -x

if [ -n "$OWNER_USERID" ]
then
    chown -R "$OWNER_USERID" "$DESTINATION_PATH"
fi

